version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    ports:
      - "5001:5001"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: todo
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: src/Dockerfile_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  postgres-data:
